### ISSUE TITLE
Add support for multiple AdvancedParams in QueryParams payload

### ISSUE THREAD

**Issue by anisbhsl** [NASA-IMPACT/pynequa#26]
Current implementation of `QueryParams` payload generation supports having only one advanced param. Refer to Sinequa's REST API docs and provide a way to support any number of advanced params. 

cc: @CarsonDavis

**Comment by CarsonDavis** [comment]
https://github.com/NASA-IMPACT/pynequa/blob/88785042cfcef9580683a7015f94b38f226078d3/pynequa/models.py#L85-L106
